### ISSUE TITLE
Petitions now has an interface with White House API

### ISSUE THREAD

**Issue by wilson428** [unitedstates/wish-list#10]
This is the "We the People" API the WH debuted at their hackathon two weeks ago, if anyone's interested. Right now there's a public API key. Data is similar to that which one can scrape, those more precise in places (Like zip codes instead of city-state for each signatory who specified one.)

**Comment by konklone** [comment]
I think you did this over in unitedstates/petitions (which is awesome).

**Comment by wilson428** [comment]
Sure did! Though I need to revisit it bc the WH has made a bunch of improvements to the API.
