### ISSUE TITLE
Shared glossary

### ISSUE THREAD

**Issue by konklone** [unitedstates/wish-list#12]
One thing that came up in a recent Sunlight brainstorm was having a glossary available to define terms, describe processes, and generally make the information we're shoving at people more understandable. ("Reported in Senate" - what does that even mean?) Maybe some sites would replace formal terminology, maybe others would just highlight them with an underline or link for more information, maybe others would go further.

There are glossaries in the House, Senate, and probably Congress.gov somewhere - it'd be nice to take the best of each, expand where necessary. An unofficial source like this could also be less formally written, and doesn't have to be as detailed or as precise as official glossaries might be under pressure to be - we can place accessibility as the # 1 priority. It doesn't have to stay limited to Congress, either.

Is there any interest in this, and if so, approaching it in the style of [unitedstates/bill-nicknames](/unitedstates/bill-nicknames), as a collaborative file anyone can use in their work?

**Comment by dwillis** [comment]
Stop having so many good ideas, Eric! +1

**Comment by konklone** [comment]
Okay, I started something:
https://github.com/unitedstates/glossary/

I don't know how to handle formatting yet, something that'd be friendly for clients to parse as they integrate it however. But if people are interested, let's discuss it there,
