### ISSUE TITLE
Local Officials

### ISSUE THREAD

**Issue by scragg0x** [unitedstates/wish-list#14]
Is it feasible to compile a list of elected officials on the city and county levels and any meta data associated with them?

I know votesmart.org does have some of this data, not sure if they just manually input, use scrapers, or a third party data source.  It's not very complete either.  They also charge some money to use their API.

What are your thoughts?

**Comment by dwillis** [comment]
Well, this is a _wish_ list, but I'd say that we could spend all of our time on just doing this.

**Comment by konklone** [comment]
Like Derek said, it's a **huge** problem, but recently there's been a huge spike of work being done by multiple organizations on exactly this. CCing @jamesturk, who's on point on a lot of related work over at @opencivicdata.

**Comment by scragg0x** [comment]
I am thinking it would be a collaborative effort with a structure like /$state/cities/$cityname.yaml and similar for counties.

@konklone I see, thanks for the link.  I took a look at the scrapers and appears to be collecting quite a bit of data and will keep an eye on the project.

I was thinking with emphasis on elected officials and being able to look up governor of state x, or the sheriff for county y, or mayor of city z.  A lot of this is on Wikipedia so it would be a good scraping target.

**Comment by dwillis** [comment]
Oh, I'm not saying it couldn't be done. In fact, I'm doing it for NYC for work right now. But as much as candidates enter and leave federal and statewide races, they do so even more at the local level. Maintenance would be very time-consuming.

**Comment by konklone** [comment]
I'm actually going to close this, since Open Civic Data is the hub for this stuff. Though I would love to integrate their (or others' work) here as it becomes reliable and available. OCD has a [mailing list](https://groups.google.com/forum/#!forum/open-civic-data) you may be interested in as well.

Do please continue opening tickets and wishing. :)
