### ISSUE TITLE
3D Visualization US Gov Org Chart

### ISSUE THREAD

**Issue by lowerkey** [unitedstates/wish-list#20]
Greetings,

I love your page, and was wondering if you could point me to resources for making a dynamic org chart of government (for use by news organizations, etc.)

The [dynamic 3D graph visualizatoin library](http://karass.github.io/kankan.js) I wrote would work well for that, I think. 

I look forward to working with your data!

~lowerkey

**Comment by konklone** [comment]
There's been some discussion of that, including this org:

https://github.com/unitedstates/orgchart/issues/1
http://opendata.stackexchange.com/questions/1/is-there-a-list-of-all-us-government-agencies-and-sub-agencies-and-is-it-availab

I think it'll take a bit of work no matter what you use, but the basics are out there. I'm going to mark the issue as closed, but feel free to re-open if you want to bring up something not discussed in those links.
