### ISSUE TITLE
Guest chaplain prayers?

### ISSUE THREAD

**Issue by wilson428** [unitedstates/wish-list#9]
Any interest in the text of the [633 guest chaplain prayers](http://chaplain.house.gov/chaplaincy/guest_chaplains.html) on the House Chaplain website? Noticed them from a @dwillis tweet on Monday.

I have an interactive coming out on these on Monday, and can link directly here to the source if desired. Otherwise will just stick on my account, no worries. Code is already done and conforms to this org's general format -- utils.py etc etc

**Comment by dwillis** [comment]
I was going to integrate just the chaplain appearances at some point, so this would be great. Do you also have their congressional sponsors? Can we hook those up with bioguide IDs?

**Comment by wilson428** [comment]
Just added a Chaplains repo -- it does pull down the sponsoring member when there is one. (About 175 of them list no sponsor.) It parses the party and state of the sponsor, but doesn't link to Bioguide. Would be extremely easy to connect the two, however. Recommendations for how to connect the repos?

**Comment by dwillis** [comment]
Couple of different ways you could approach it - you could use the current & former legislators file, or the NYT API's list of members for a specific congress and then match on last name, state and party.

**Comment by wilson428** [comment]
I took a pass at a member lookup function using the Times API, in member_lookup.py in the chaplains repo. Might be useful for other projects. Right now it can handle modestly ambivalent names (Sheila Jackson Lee or Jackson-Lee?) and misspelled names that are one edit distance away from being correct. (The House Chaplain site is rather sloppy).
